name: external_handler
on: repository_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - env: 
          GH_TOKEN: ${{ github.token }}
      - name: Test
        run: |
          echo "received the event"
          gh workflow run
      - uses: actions/checkout@v3
