name: external_handler
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - env: 
           GH_TOKEN: ${{ github.token }}
         run: |
           echo "received the event"
           gh workflow run
         name: handler
       - uses: actions/checkout@v3
     
