name: external_handler
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - env: 
         GH_TOKEN: ${{ github.token }}
       run: |
         echo "somethings"
         
     - uses: actions/checkout@v3
     
