name: workflow2
on: 
  repository_dispatch:
  workflow_dispatch:
   inputs: 
      name:
jobs:
  build:
    if: "github.event.inputs.name == 'lambda'"
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
         echo "Im triggered"
      - uses: actions/checkout@v2
