name: workflow2
on: 
  repository_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
         echo "Im triggered"
      - uses: actions/checkout@v3
